spring:
  mail:
    host: smtp.163.com
    username: s@163.com
    password: sss
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
